name: CI

on:
  push:
    branches:
      - master

jobs:
  setup:
    name: SetUp
    runs-on: ubuntu-18.04
    outputs:
      docker_image: ${{ steps.set-image.outputs.docker_image }}
    steps:
    - name: SetImage
      id: set-image
      run: |
        echo "::set-output name=docker_image::36rafts/nukegara-box:latest"

  test-cache:
    name: TestCache
    runs-on: ubuntu-18.04
#    container:
#      image: ${{ needs.image.outputs.docker_image }}

    steps:
    - name: echo
      run: |
        echo ${{ needs.setup.outputs.docker_image }}

      #    - name: Started Job
      #      uses: 8398a7/action-slack@v3
      #      if: always()
      #      with:
      #        status: ${{ job.status }}
      #        fields: repo,message,commit,author
      #        author_name: Started TestCache
      #        mention: here
      #        if_mention: failure,cancelled
      #        channel: '#deploy'
      #      env:
      #        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

#    - name: init for cache
#      run: |
#        mkdir -p $GOPATH/pkg/mod
#
#    - name: before cache-restore
#      run: |
#        echo "~"
#        ls -al ~/
#        echo "HOME: $HOME"
#        ls -al $HOME
#        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
#        ls -al $GITHUB_WORKSPACE
#        echo "GOPATH: $GOPATH"
#        ls -al $GOPATH
#        echo "$GOPATH/src/nukegara"
#        ls -al $GOPATH/src/nukegara
#        echo "$GOPATH/pkg/mod"
#        ls -al $GOPATH/pkg/mod
#
#    - uses: actions/cache@v2
#      id: test-cache
#      env:
#        cache-name: go-mod-cache
#      with:
#        path: /go/pkg/mod
#        key: ${{ runner.os }}-build-${{ env.cache-name }}-
#        restore-keys: |
#          ${{ runner.os }}-build-${{ env.cache-name }}-
#          ${{ runner.os }}-build-
#
#    - name: after cache-restore
#      run: |
#        echo "~"
#        ls -al ~/
#        echo "HOME: $HOME"
#        ls -al $HOME
#        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
#        ls -al $GITHUB_WORKSPACE
#        echo "GOPATH: $GOPATH"
#        ls -al $GOPATH
#        echo "$GOPATH/src/nukegara"
#        ls -al $GOPATH/src/nukegara
#        echo "$GOPATH/pkg/mod"
#        ls -al $GOPATH/pkg/mod
#
#    - name: go_mod_download
#      if: steps.test-cache.outputs.cache-hit != 'true'
#      run: |
#        cd $GOPATH/src/nukegara
#        go mod download
#
#    - name: after write test-data
#      run: |
#        echo "~"
#        ls -al ~/
#        echo "HOME: $HOME"
#        ls -al $HOME
#        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
#        ls -al $GITHUB_WORKSPACE
#        echo "GOPATH: $GOPATH"
#        ls -al $GOPATH
#        echo "$GOPATH/src/nukegara"
#        ls -al $GOPATH/src/nukegara
#        echo "$GOPATH/pkg/mod"
#        ls -al $GOPATH/pkg/mod
