name: CI

on:
  push:
    branches:
      - master

jobs:
  test-cache:
    name: TestCache
    runs-on: ubuntu-18.04
    container:
      image: 36rafts/nukegara:latest

    steps:
      #    - name: Started Job
      #      uses: 8398a7/action-slack@v3
      #      if: always()
      #      with:
      #        status: ${{ job.status }}
      #        fields: repo,message,commit,author
      #        author_name: Started TestCache
      #        mention: here
      #        if_mention: failure,cancelled
      #        channel: '#deploy'
      #      env:
      #        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: before cache-restore
      run: |
        echo "~"
        ls -al ~/
        echo "HOME: $HOME"
        ls -al $HOME
        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
        ls -al $GITHUB_WORKSPACE

    - uses: actions/cache@v2
      id: test-cache
      env:
        cache-name: cache-text
      with:
        path: ~/.testcache
        key: ${{ runner.os }}-build-${{ env.cache-name }}-
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-

    - name: after cache-restore
      run: |
        echo "~"
        ls -al ~/
        echo "HOME: $HOME"
        ls -al $HOME
        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
        ls -al $GITHUB_WORKSPACE

    - name: write test-data
      if: steps.test-cache.outputs.cache-hit != 'true'
      run: |
        mkdir ~/.testcache
        echo "testtesttest" > ~/.testcache/test.txt

    - name: after write test-data
      run: |
        echo "~"
        ls -al ~/
        echo "HOME: $HOME"
        ls -al $HOME
        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
        ls -al $GITHUB_WORKSPACE
