name: CI

on:
  push:
    branches:
      - master

jobs:
  test-cache:
    name: TestCache
    runs-on: ubuntu-18.04
    container:
      image: 36rafts/nukegara-box:latest

    steps:
      #    - name: Started Job
      #      uses: 8398a7/action-slack@v3
      #      if: always()
      #      with:
      #        status: ${{ job.status }}
      #        fields: repo,message,commit,author
      #        author_name: Started TestCache
      #        mention: here
      #        if_mention: failure,cancelled
      #        channel: '#deploy'
      #      env:
      #        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: init for cache
      run: |
        mkdir -p $GOPATH/pkg/mod
        ln -s $GOPATH/pkg/mod .go_mod_cache

    - name: before cache-restore
      run: |
        echo "~"
        ls -al ~/
        echo "HOME: $HOME"
        ls -al $HOME
        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
        ls -al $GITHUB_WORKSPACE
        echo "GOPATH: $GOPATH"
        ls -al $GOPATH
        echo "$GOPATH/src/nukegara"
        ls -al $GOPATH/src/nukegara
        echo "$GOPATH/pkg"
        ls -al $GOPATH/pkg
        echo ".go_mod_cache"
        ls -al .go_mod_cache

    - uses: actions/cache@v2
      id: test-cache
      env:
        cache-name: .go-mod-cache
      with:
        path: .go_mod_cache
        key: ${{ runner.os }}-build-${{ env.cache-name }}-
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-

    - name: after cache-restore
      run: |
        echo "~"
        ls -al ~/
        echo "HOME: $HOME"
        ls -al $HOME
        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
        ls -al $GITHUB_WORKSPACE
        echo "GOPATH: $GOPATH"
        ls -al $GOPATH
        echo "$GOPATH/src/nukegara"
        ls -al $GOPATH/src/nukegara
        echo "$GOPATH/pkg"
        ls -al $GOPATH/pkg
        echo ".go_mod_cache"
        ls -al .go_mod_cache

    - name: go_mod_download
      if: steps.test-cache.outputs.cache-hit != 'true'
      run: |
        go mod download

    - name: after write test-data
      run: |
        echo "~"
        ls -al ~/
        echo "HOME: $HOME"
        ls -al $HOME
        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
        ls -al $GITHUB_WORKSPACE
        echo "GOPATH: $GOPATH"
        ls -al $GOPATH
        echo "$GOPATH/src/nukegara"
        ls -al $GOPATH/src/nukegara
        echo "$GOPATH/pkg"
        ls -al $GOPATH/pkg
        echo ".go_mod_cache"
        ls -al .go_mod_cache
